#ifndef LIBRENDER_DRAWABLE_UPDATE_H
# define LIBRENDER_DRAWABLE_UPDATE_H

# define DRAWABLE_UPDATE_VERTEXES	0x01
# define DRAWABLE_UPDATE_TEX_COORDS	0x02
# define DRAWABLE_UPDATE_COLORS		0x04
# define DRAWABLE_UPDATE_INDICES	0x08

#endif
